# Use the official Node.js image as the base image
FROM node:lts-alpine3.21

# Create app directory
WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./
COPY --chown=node:node tsconfig*.json ./

RUN npm cache clean --force
RUN npm install --force 

COPY --chown=node:node . .

RUN chown -R node .

USER node

EXPOSE 3000

# RUN npm run start:dev
CMD ["npm", "run", "dev"]
