services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-net
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/skidoodle -schemas=public -user=postgres -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
    networks:
      - app-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-net
  server:
    container_name: skidoodle-server
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
      - auth-server
    networks:
      - app-net
  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile.local
    ports:
      - "3002:3000"
    volumes:
      - ./auth-server:/usr/src/app
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:secretpassword@mongodb:27017/authdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-net
  mongodb:
    image: mongo:latest
    build:
      context: ./auth-database
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-net
  mongoadmin:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:secretpassword@mongodb:27017/authdb?authSource=admin"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secretpassword
    depends_on:
      - mongodb
    ports:
      - "3001:8081"
    networks:
      - app-net
  file-store:
    build:
      context: ./file-store
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./file-store:/usr/src/app
      - ./file-store/frames:/usr/src/app/frames
    depends_on:
      - server
    networks:
      - app-net
    environment:
      - PORT=3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    ports:
      - "3004:3000"
    depends_on:
      - server
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
volumes:
  db:
  pgadmin:
  mongodb-data:
