services:
  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile.local

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/usr/src/app
