import type { Metadata } from "next";
import { Bangers, Geist, Geist_Mono } from "next/font/google";

import ConfigureAmplifyClientSide from "../custom/utils/amplify-cognito-config-client";
import "./globals.css";

const heading = Bangers({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skidoodle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`${heading.variable} ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}
